### ISSUE TITLE
How do you get the auth_verifier?

### ISSUE THREAD

**Issue by Julioacarrettoni** [michaelhelmick/linkedin#1]
I did not understand what you meant by:
# oauth_token = request.GET.get('oauth_verifier')
# oauth_verifier = request.GET.get('oauth_verifier')

I know that is I input the auth_url on the browser while I´m logged on I can get the outh verifier number, but how can I do this programatically? I´m sorry if this sounds dumb, I´m relatively new in Python

**Comment by michaelhelmick** [comment]
Are you using a Python framework like Flask or Django?

**Comment by Julioacarrettoni** [comment]
Ohhh, I get it. This has something to do with the front end, I´m on the back end. So I need someone to ask the user to log in on the app and THEN get the auth_verifier number

**Comment by michaelhelmick** [comment]
Yep. You send the user to the auth_url (like in my README) and then on the callback url, you would programmatically obtain the oauth_token and oauth_verifier from the url. I had a typo in my README, and have updated it, should read:

``` python
oauth_token = request.GET.get('oauth_token')
oauth_verifier = request.GET.get('oauth_verifier')
```

Let me know if you understand and end up getting it to work! :)

**Comment by Julioacarrettoni** [comment]
Thank you, I got to work now. Now I have a different issue. When I try to obtain the network updates of the user like this:

# Get your network updates

feed = l.get('people/~/network/updates')
print feed

All I get is : {'_total': 0}

I tried posting and getting profile information, they all worked fine. Am I doing something wrong?

**Comment by michaelhelmick** [comment]
Try and add do:

``` python
feed = l.get('people/~/network/updates', params={'count':100})
print feed
```

If that doesn't work, make sure you actually have people connecting/posting updates in your feed on http://linkedin.com

**Comment by Julioacarrettoni** [comment]
I got it to work. 

Thanks for all your help ^_^

**Comment by michaelhelmick** [comment]
Right! That will grab all of your posts instead of your connections posts. Glad you got it to work! ^_^
